### ISSUE TITLE
[feature] Implement other graphql request

### ISSUE THREAD

**Issue by NoBraincellsLeft** [Electronic-Mango/simple-justwatch-python-api#4]
2 queries I would love to see in this library

GetTitleOffers (with a list of countries as input):
```
private static string _GetTitleOffersQuery(IEnumerable<string> countries)
	{
		string query = @"
query GetTitleOffers($nodeId: ID!, $language: Language!, $filterBuy: OfferFilter!, $platform: Platform! = WEB) {
  node(id: $nodeId) {

    ... on MovieOrShowOrSeasonOrEpisode {
      
      ";

		foreach (var country in countries)
		{
			query += $@"
      {country.ToLower()}: offers(country: {country}, platform: $platform, filter: $filterBuy) {{
        ...TitleOffer
        __typename
      }}";
		}
		query += @"
    }
  }
}

fragment TitleOffer on Offer {
  id
  presentationType
  monetizationType
  retailPrice(language: $language)
  retailPriceValue
  currency
  lastChangeRetailPriceValue
  type
  package {
    id
    packageId
    clearName
    technicalName
    icon(profile: S100)
    __typename
  }
  standardWebURL
  elementCount
  availableTo
  deeplinkRoku: deeplinkURL(platform: ROKU_OS)
  subtitleLanguages
  videoTechnology
  audioTechnology
  audioLanguages
  __typename
}";

		return query;
	}

```

This one is maybe also handy to get details by the NodeID
```
query GetTitleNode(
  $nodeId: ID!, 
  $language: Language!, 
  $country: Country!,
  $formatPoster: ImageFormat,
  $profile: PosterProfile,
  $backdropProfile: BackdropProfile) {
  node(id: $nodeId) {
 
   ... on MovieOrShow {
    id
    objectId
    objectType
    content(country: $country, language: $language) {
      title
      fullPath
      originalReleaseYear
      originalReleaseDate
      runtime
      shortDescription
      genres {
        shortName
        __typename
      }
      externalIds {
        imdbId
        tmdbId
        __typename
      }
      posterUrl(profile: $profile, format: $formatPoster)
      backdrops(profile: $backdropProfile, format: $formatPoster) {
        backdropUrl
        __typename
      }
      __typename
    }

    __typename
  }
}
}
```

**Comment by Electronic-Mango** [comment]
Just an FYI that I started to work on this.

I'll probably update current "search" query to have all fields from those new queries. This way data structures between queries should match.

BTW, what's the use case of getting details by ID? I thought about this when I was initially working on this project, but ID isn't easily accesses outside of a "search" query and I can put all data from dedicated "details" query into the "search" query, making the "details" query kinda obsolete.

**Comment by NoBraincellsLeft** [comment]
It makes it easier to store, otherwise you have to do a search query again to find the right title. 
A example for a use case I use it currently is to make the page refreshable, it does the GetTitleNode query when I access this page directly. 
https://nobraincellsleft.github.io/JustWatch-Search/title/ts43075

**Comment by Electronic-Mango** [comment]
That's a good point, I'll add it as well.

I'll also add available offers to "details by ID" request, as it needs country code and language anyways, so why not.
This way it will match output from search command, just for a single entry.

**Comment by Electronic-Mango** [comment]
I've uploaded version [0.14](https://pypi.org/project/simple-justwatch-python-api/0.14/) which have 2 new functions:

 * [`details`](https://electronic-mango.github.io/simple-justwatch-python-api/simplejustwatchapi.html#simplejustwatchapi.justwatch.details) - uses `GetTitleNode` query to get data for a single entry
 * [`offers_for_countries`](https://electronic-mango.github.io/simple-justwatch-python-api/simplejustwatchapi.html#simplejustwatchapi.justwatch.offers_for_countries) - uses `GetTitleOffers` query to get offers for a single entry, you can specify multiple countries to look up via a set of codes as one of the arguments

Let me know if that covers everything.
