### ISSUE TITLE
[feature] search function by URL?

### ISSUE THREAD

**Issue by b-gonzalez** [Electronic-Mango/simple-justwatch-python-api#9]
In my current process, I search for a movie on JustWatch by using the title. If there are multiple titles that match this name, multiple media entries are returned. To find the media entry that I'm looking for, I can use the URL to filter for the media entry that contains the matching URL. But I was wondering if the search functionality could be updated to search by URLs. This would remove my need to loop through media entries to find the matching one.

**Comment by dseomn** [comment]
Do you want to search URLs, or just get the info for what's at a specific URL? If the latter, here's some code that does it in case that helps: https://github.com/dseomn/rock-paper-sand/blob/942db488291dfec9f91c7f3365dd92d7d3fbbd9a/rock_paper_sand/justwatch.py#L239-L245

**Comment by b-gonzalez** [comment]
I wanted to be able to search by URLs. I was able to get the code that you linked to working. Although I had to implement all of the code in the `query_document ` variable as opposed to just the snippet you linked to. The data in the JSON returned is data like this:

```{"data":{"urlV2":{"node":{"__typename":"Movie","id":"tm10","offers":[{"monetizationType":"FLATRATE","availableToTime":"2024-08-01T07:00:00Z","availableFromTime":null,"package":{"clearName":"Netflix","technicalName":"netflix"}},{"monetizationType":"FLATRATE","availableToTime":"2024-08-01T07:00:00Z","availableFromTime":null,"package":{"clearName":"Netflix","technicalName":"netflix"}},{"monetizationType":"FLATRATE","availableToTime":"2024-08-01T07:00:00Z","availableFromTime":null,"package":{"clearName":"Netflix basic with Ads","technicalName":"netflixbasicwithads"}},{"monetizationType":"FLATRATE","availableToTime":"2024-08-01T07:00:00Z","availableFromTime":null,"package":{"clearName":"Netflix basic with Ads","technicalName":"netflixbasicwithads"}},{"monetizationType":"CINEMA","availableToTime":null,```

But I'm trying to get data like this:

```{"data":{"popularTitles":{"edges":[{"node":{"id":"tm10","objectId":10,"objectType":"MOVIE","content":{"title":"The Matrix","fullPath":"/us/movie/the-matrix","originalReleaseYear":1999,"originalReleaseDate":"1999-03-31","runtime":136,"shortDescription":"Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.","genres":[{"shortName":"scf","__typename":"Genre"},{"shortName":"act","__typename":"Genre"}],"externalIds":{"imdbId":"tt0133093","__typename":"ExternalIds"},"posterUrl":"/poster/140351543/s718/the-matrix.jpg"```

And like this:

```{"id":"b2Z8dG0xMDpVUzoyOnJlbnQ6aGQ=","monetizationType":"RENT","presentationType":"HD","retailPrice":"$3.99","retailPriceValue":3.99,"currency":"USD","lastChangeRetailPriceValue":null,"type":"STANDARD","package":{"id":"cGF8Mg==","packageId":2,"clearName":"Apple TV","technicalName":"itunes","icon":"/icon/190848813/s100/itunes.png","__typename":"Package"}```

**Comment by dseomn** [comment]
At a glance, that looks like it's all from the same thing being returned, you'd just have to request the fields you want.

**Comment by b-gonzalez** [comment]
Ah okay. Thanks for the heads up. I'm not super familiar with GraphQL. After some trial and error it looks like I was able to merge the code in both codebases to pull the offer data by the URL. I created a new variable like this:

```python
  _GRAPHQL_SEARCH_URL_QUERY = """
    fragment Movie on MovieOrShow {
        __typename
        id
        offers(country: $country, platform: WEB) {
          monetizationType
          presentationType
          retailPriceValue
          currency
          lastChangeRetailPriceValue
          type
          package {
            id
            packageId
            clearName
            technicalName
            __typename
          }
        }
    }
  
    fragment Node on Node {
        __typename
        id
        ...Movie
    }
  
    query GetNodeByUrlPath($urlPath: String!, $country: Country!) {
        urlV2(fullPath: $urlPath) {
            node {
                ...Node
            }
        }
    }
  """
```

I had to remove certain parameters to make this work. I wasn't able to get the movie description info to work yet due to parameter issues. But I'm continuing to work on it.
